version: '3.8'

services:
  # MySQL database server
  db:
    image: mysql:8.0
    container_name: smarterp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_DATABASE: "smart_erp"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # Flask Web backend and assets
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: smarterp_web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=12345678
      - DB_NAME=smart_erp
      - GEMINI_API_KEY=""
    depends_on:
      - db

volumes:
  mysql_data:
